apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-assingment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-assingment
  template:
    metadata:
      labels:
        app: jenkins-assingment
    spec:
      containers:
      - name: jenkins-assignment
        image: public.ecr.aws/x3l3p6p0/jenkins-assingment:latest
        ports:
        - containerPort: 8080
